export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const CLEAR_COMPOSITION = 'CLEAR_COMPOSITION';

export const SORT_INGREDIENTS = 'SORT_INGREDIENTS';
