export enum OrderActionType {
  TAKE_ORDER_REQUEST = 'TAKE_ORDER_REQUEST',
  TAKE_ORDER_SUCCESS = 'TAKE_ORDER_SUCCESS',
  TAKE_ORDER_FAILED = 'TAKE_ORDER_FAILED',

  CLEAR_ORDER_NUMBER = 'CLEAR_ORDER_NUMBER',
}
